server:
  port: 8080

spring:
  datasource:
    username: root
    password: SWKOTOR32
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Lenta.ru
#    - url: https://skillbox.ru/
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru


crawler-setting:
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (HTML, like Gecko) Chrome/74.0.3729.169 Safari/537.3"
  referrer: "https://www.google.com"
  delay-between-requests: [1200, 2000]